#########################################################################
# Title:         Saltbox: Resources | Tasks | Instances | Get Info      #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Default Radarr variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/radarr/defaults/main.yml
  when: radarr_instances is undefined

- name: Import Default Sonarr variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/sonarr/defaults/main.yml
  when: sonarr_instances is undefined

- name: Import Default Lidarr variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/lidarr/defaults/main.yml
  when: lidarr_instances is undefined

- name: Import Default Readarr variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/readarr/defaults/main.yml
  when: readarr_instances is undefined

- name: Resources | Tasks | Instances | Get Info | Run Sonarr Tasks
  ansible.builtin.include_tasks: sonarr.yml
  vars:
    sonarr_name: "{{ role }}"
  with_items: "{{ sonarr_instances }}"
  loop_control:
    loop_var: role

- name: Resources | Tasks | Instances | Get Info | Run Radarr Tasks
  ansible.builtin.include_tasks: radarr.yml
  vars:
    radarr_name: "{{ role }}"
  with_items: "{{ radarr_instances }}"
  loop_control:
    loop_var: role

- name: Resources | Tasks | Instances | Get Info | Run Lidarr Tasks
  ansible.builtin.include_tasks: lidarr.yml
  vars:
    lidarr_name: "{{ role }}"
  with_items: "{{ lidarr_instances }}"
  loop_control:
    loop_var: role

- name: Resources | Tasks | Instances | Get Info | Run Readarr Tasks
  ansible.builtin.include_tasks: readarr.yml
  vars:
    readarr_name: "{{ role }}"
  with_items: "{{ readarr_instances }}"
  loop_control:
    loop_var: role
