#########################################################################
# Title:         Cloudbox: Nginx Role                                   #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# Docker Image:  linuxserver/nginx                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create DNS Record
  include_role:
    name: dns
  vars:
    dns_record: "{{ nginx_web_subdomain }}"
    dns_zone: "{{ nginx_web_domain }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent

- name: Create directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"