#########################################################################
# Title:         Saltbox: Nginx Role                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Nginx roles"
  include_tasks: main2.yml
  vars:
    nginx_name: "{{ role }}"
  with_items: "{{ nginx_instances }}"
  loop_control:
    loop_var: role
