#########################################################################
# Title:         Pre-Tasks: Folders Task                                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create Ansible Temp directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - /srv/ansible
    - /srv/ansible/tmp

- name: Chown '/srv'
  file:
    path: /srv
    state: directory
    recurse: true
    owner: uid
    group: gid