#########################################################################
# Title:         Pre-Tasks: Git Task                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Git | Set Saltbox & Sandbox as safe directories
  ansible.builtin.shell: git config --global --add safe.directory "{{ item }}"
  loop:
    - "/srv/git/saltbox"
    - "/srv/git/sb"
