#########################################################################
# Title:         Pre-Tasks: Git Task                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Git | Lookup git safe directories
  shell: git config --global -l
  register: git_config
  ignore_errors: true

- name: Git | Set Saltbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/saltbox
  when: not '/srv/git/saltbox' in test.stdout

- name: Git | Set sb repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/sb
  when: not '/srv/git/sb' in test.stdout

- name: Git | Set Sandbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /opt/sandbox
  when: not '/opt/sandbox' in test.stdout
