#########################################################################
# Title:         Saltbox: UnionFS | Mount Path Tasks                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Mount Path | Force unmount '/mnt/unionfs'"
  shell: "/bin/umount -f '/mnt/unionfs' 2>/dev/null || :"
  ignore_errors: true

- name: "Mount Path | Check if '/mnt/unionfs' exists"
  stat:
    path: "/mnt/unionfs"
  register: mnt_unionfs
  ignore_errors: true

- name: "Mount Path | Tasks for '/mnt/unionfs' path"
  block:

    - name: "Mount Path | Remove empty directories in '/mnt/unionfs'"
      shell: "find '/mnt/unionfs' -type d -empty -delete"
      ignore_errors: true

    - name: "Mount Path | Recursively find '/mnt/unionfs' files"
      find:
        paths: "/mnt/unionfs"
        hidden: true
        recurse: true
      register: mnt_unionfs_files

    - name: "Mount Path | Backup non-empty '/mnt/unionfs' path"
      shell: "mv /mnt/unionfs /mnt/unionfs_{{ '%Y-%m-%d_%H.%M.%S' | strftime(ansible_date_time['epoch']|int) }}"
      ignore_errors: true
      when: (mnt_unionfs_files.matched|int > 0)

    - name: "Mount Path | Remove '/mnt/unionfs'"
      file:
        path: "/mnt/unionfs"
        state: absent

    - name: "Mount Path | Create '/mnt/unionfs' directory"
      file:
        path: "/mnt/unionfs"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"
        recurse: true

  when: (mnt_unionfs is failed) or (mnt_unionfs.stat.exists)

- name: "Mount Path | Create '/mnt/unionfs' directory"
  file:
    path: "/mnt/unionfs"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true
  when: (not mnt_unionfs.stat.exists)
