#########################################################################
# Title:         Saltbox: Sanity Check | Tmp Folder                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Tmp | Create Ansible Temp directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    owner: "root"
    group: "root"
  with_items:
    - /tmp/ansible
