#########################################################################
# Title:         Saltbox: Sanity Check | Settings                       #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Settings | Ensure TLS validation isn't used with ZeroSSL
  assert:
    that:
      - sanity_check_settings_check
    fail_msg: "You cannot currently use TLS validation together with ZeroSSL"
    success_msg: "Not using TLS validation with ZeroSSL"
