#########################################################################
# Title:            Saltbox: MongoDB                                    #
# Author(s):        Superduper09, desimaniac, salty                     #
# URL:              https://github.com/saltyorg/Saltbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Fail if dash is present in instance name."
  ansible.builtin.fail:
    msg: "Dashes are not allowed in instance name as it breaks variable overrides."
  when: "'-' in mongodb_name"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Sleep for 30 seconds
  ansible.builtin.wait_for:
    timeout: 30
