---
version: 1.0.0-{build}

build_cloud: CLOUDBOX

image: 
  - Ubuntu1804
  - Ubuntu2004

matrix:
  fast_finish: false

# to disable automatic builds and tests
build: off
test: off

init:
  - sh: curl -s https://raw.githubusercontent.com/saltyorg/sb/master/sb_dep.sh | sudo -H bash
  - sh: sudo mkdir /srv/git
  - sh: sudo ln -s /home/appveyor/projects/saltbox /srv/git/saltbox
  - sh: sudo chown -R appveyor:appveyor /srv/git

install:
  - sh: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done
  - sh: curl -o daemon.json https://raw.githubusercontent.com/saltydk/AppveyorTest/main/daemon.json
  - sh: cp -f daemon.json /home/appveyor/projects/saltbox/roles/docker/templates/daemon.json.j2
  - sh: sudo ansible-playbook saltbox.yml --syntax-check
  - sh: |
      sudo ansible-playbook saltbox.yml --tags "saltbox,emby,netdata,sabnzbd" \
          --skip-tags "settings,plex-extra-tasks" \
          --extra-vars '{"continuous_integration":true}'
