#########################################################################
# Title:         Saltbox: User Role                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: User Account
  import_tasks: "subtasks/user_account.yml"
