#########################################################################
# Title:         Saltbox: Media Server Role                             #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Media Server roles"
  include_role:
    name: "{{ role }}"
  with_items: "{{ media_servers_enabled }}"
  loop_control:
    loop_var: role
