#########################################################################
# Title:         Saltbox: Docker | Default Variables                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Docker APT Key
################################

docker_apt_key_id: 0EBFCD88

docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg

################################
# Docker APT Repository
################################

docker_apt_repo_version: stable

docker_apt_repo_url: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_repo_version }}"

docker_apt_repo_filename: docker

################################
# Docker APT Package
################################

# Version

docker_version: "latest"

# Docker CE

docker_ce_name: "Docker CE"

docker_ce_package: "{{ 'docker-ce' if (docker_version is defined and docker_version | lower == 'latest')
                    else 'docker-ce=*' + docker_version + '*~' + ansible_distribution | lower + '-' + ansible_distribution_release | lower }}"

docker_ce_filepath: "/usr/bin/dockerd"

docker_ce_dpkg: "docker-ce"

# Docker CE CLI

docker_ce_cli_name: "Docker CE CLI"

docker_ce_cli_package: "{{ 'docker-ce-cli' if (docker_version is defined and docker_version | lower == 'latest')
                        else 'docker-ce-cli=*' + docker_version + '*~' + ansible_distribution | lower + '-' + ansible_distribution_release | lower }}"

docker_ce_cli_filepath: "/usr/bin/docker"

docker_ce_cli_dpkg: "docker-ce-cli"

# Containerd

containerd_io_name: "Containerd"

containerd_io_package: "containerd.io"

containerd_io_filepath: "/usr/bin/containerd"

containerd_io_dpkg: "containerd.io"

# Misc

docker_package_state: "{{ 'latest' if (docker_version is defined and docker_version | lower == 'latest') else 'present' }}"

put_docker_dpkg_into_hold: true

# Service

docker_service_after: "{{ mount_type }}.service"

docker_service_sleep: 120
