#########################################################################
# Title:         Cloudbox: Nvidia | Patch Tasks                         #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox2/cloudbox                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Patch | Download Nvidia patch
  get_url:
    url: "{{ nvidia_patch_download_url }}"
    dest: "{{ nvidia_patch_download_dest }}"
    mode: 0775
    owner: root
    group: root
    force: true
    validate_certs: false

- name: Patch | Install Nvidia patch
  shell: "{{ nvidia_patch_download_dest }}"
  args:
    executable: /bin/bash
    warn: false
  register: patch_install
  ignore_errors: true

- name: Patch | Nvidia patch installed
  debug:
    msg: "Nvidia patch installed!"
  when: (patch_install is succeeded) and ('Patched!' in patch_install.stdout)

- name: Patch | Nvidia patch did not install
  fail:
    msg:
      - "Nvidia patch did not install!"
      - "{{ patch_install.stdout }}"
  when: (patch_install is failed) or ('Patched!' not in patch_install.stdout)
