#########################################################################
# Title:         Saltbox: Trackarr | Pre-Install Tasks                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Check if Trackarr config exists
  stat:
    path: "{{ trackarr_paths_config_location }}"
  register: trackarr_paths_config_location_stat

- name: Pre-Install | New Trackarr config tasks
  block:

    - name: Pre-Install | Get ARR API keys
      include_tasks: "{{ resources_tasks_path }}/arr/get_api_keys.yml"
      vars:
        sonarr_name: "{{ sonarr_instances[0] }}"
        radarr_name: "{{ radarr_instances[0] }}"
        lidarr_name: "{{ lidarr_instances[0] }}"

    - name: Pre-Install | Set 'trackarr_server_apikey' variable
      set_fact:
        trackarr_server_apikey: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=22') }}"

    - name: Pre-Install | Import default Trackarr config
      template:
        src: "config.yaml.j2"
        dest: "{{ trackarr_paths_config_location }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"
        force: false

    - name: Pre-Install | Set 'trackarr_docker_state' variable
      set_fact:
        trackarr_docker_state: "stopped"

  when: not trackarr_paths_config_location_stat.stat.exists
