#########################################################################
# Title:         Cloudbox: Lidarr Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/lidarr                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create DNS Record
  include_role:
    name: dns
  vars:
    record: "{{ subdomain }}"
  when: reverse_proxy_is_enabled

- name: Remove existing Docker container
  docker_container:
    name: "{{ docker_name }}"
    state: absent

- name: Hotio Migration Tasks
  import_tasks: "{{ playbook_dir }}/resources/tasks/hotio-migration/main.yml"

- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items: "{{ folders }}"

- name: Create Docker container
  include_tasks: "{{ playbook_dir }}/resources/tasks/docker/create_docker_container.yml"
