##########################################################################
# Title:         Saltbox: Emby | Default Variables                       #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

emby_name: emby

################################
# Paths
################################

emby_paths_folder: "{{ emby_name }}"
emby_paths_location: "{{ server_appdata_path }}/{{ emby_paths_folder }}"
emby_paths_transcodes_location: "{{ transcodes_path }}/{{ emby_paths_folder }}"
emby_paths_folders_list:
  - "{{ emby_paths_location }}"
  - "{{ emby_paths_location }}/config"
  - "{{ emby_paths_location }}/config/users"
  - "{{ emby_paths_transcodes_location }}"
emby_paths_config_location: "{{ emby_paths_location }}/config/system.xml"
emby_paths_dlna_xml_location: "{{ emby_paths_location }}/config/dlna.xml"

################################
# Web
################################

emby_web_subdomain: "{{ emby_name }}"
emby_web_domain: "{{ user.domain }}"
emby_web_port: "8096"
emby_web_url: "{{ 'https://' + emby_web_subdomain + '.' + emby_web_domain
               if (reverse_proxy_is_enabled)
               else 'http://localhost:' + emby_web_port }}"

################################
# DNS
################################

emby_dns_record: "{{ emby_web_subdomain }}"
emby_dns_zone: "{{ emby_web_domain }}"
emby_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

emby_traefik_middleware: "{{ traefik_default_middleware }}"
emby_traefik_certresolver: "{{ traefik_default_certresolver }}"
emby_traefik_enabled: true

################################
# Settings
################################

emby_config_cache_size: 1024

emby_config_settings_default:
  - { xpath: 'IsBehindProxy', value: 'true' }
  - { xpath: 'WanDdns', value: '{{ emby_web_subdomain }}.{{ emby_web_domain }}' }
  - { xpath: 'PublicPort', value: '80' }
  - { xpath: 'PublicHttpsPort', value: '443' }
  - { xpath: 'EnableHttps', value: 'true' }
  - { xpath: 'RequireHttps', value: 'false' }
  - { xpath: 'EnableUPnP', value: 'false' }
  - { xpath: 'DatabaseCacheSizeMB', value: '{{ emby_config_cache_size }}' }

emby_config_settings_custom: []

emby_config_settings_list: "{{ emby_config_settings_default + emby_config_settings_custom }}"

################################
# Docker
################################

# Container
emby_docker_container: "{{ emby_name }}"

# Image
emby_docker_image_pull: true
emby_docker_image_tag: "latest"
emby_docker_image: "lscr.io/linuxserver/emby:{{ emby_docker_image_tag }}"

# Ports
emby_docker_ports_defaults:
  - "{{ emby_web_port }}:{{ emby_web_port }}"
emby_docker_ports_custom: []
emby_docker_ports: "{{ emby_docker_ports_defaults
                       + emby_docker_ports_custom
                    if (not reverse_proxy_is_enabled)
                    else [] + emby_docker_ports_custom }}"

# Envs
emby_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  NVIDIA_DRIVER_CAPABILITIES: "{{ 'compute,video,utility' if (gpu.nvidia) | default(false) else omit }}"
  NVIDIA_VISIBLE_DEVICES: "{{ 'all' if (gpu.nvidia) | default(false) else omit }}"
  TZ: "{{ tz }}"
emby_docker_envs_custom: {}
emby_docker_envs: "{{ emby_docker_envs_default
                      | combine(emby_docker_envs_custom) }}"

# Commands
emby_docker_commands_default: []
emby_docker_commands_custom: []
emby_docker_commands: "{{ emby_docker_commands_default
                          + emby_docker_commands_custom }}"

# Volumes
emby_docker_volumes_default:
  - "{{ emby_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/mnt/unionfs/Media:/data"
  - "/mnt:/mnt"
  - "/dev/shm:/dev/shm"
  - "{{ emby_paths_transcodes_location }}:/transcode"
emby_docker_volumes_custom: []
emby_docker_volumes: "{{ emby_docker_volumes_default
                         + emby_docker_volumes_custom
                         + docker_volumes_downloads_common }}"

# Mounts
emby_docker_mounts_default:
  - target: /tmp
    type: tmpfs
emby_docker_mounts_custom: []
emby_docker_mounts: "{{ emby_docker_mounts_default
                        + emby_docker_mounts_custom }}"

# Devices
emby_docker_devices_default: []
emby_docker_devices_custom: []
emby_docker_devices: "{{ emby_docker_devices_default
                         + emby_docker_devices_custom }}"

# Hosts
emby_docker_hosts_default: []
emby_docker_hosts_custom: []
emby_docker_hosts: "{{ docker_hosts_common
                       | combine(emby_docker_hosts_default)
                       | combine(emby_docker_hosts_custom) }}"

# Labels
emby_docker_labels_default: {}
emby_docker_labels_custom: {}
emby_docker_labels: "{{ docker_labels_common
                        | combine(emby_docker_labels_default)
                        | combine(emby_docker_labels_custom) }}"

# Hostname
emby_docker_hostname: "{{ emby_name }}"

# Networks
emby_docker_networks_alias: "{{ emby_name }}"
emby_docker_networks_default: []
emby_docker_networks_custom: []
emby_docker_networks: "{{ docker_networks_common
                          + emby_docker_networks_default
                          + emby_docker_networks_custom }}"

# Capabilities
emby_docker_capabilities_default: []
emby_docker_capabilities_custom: []
emby_docker_capabilities: "{{ emby_docker_capabilities_default
                              + emby_docker_capabilities_custom }}"

# Security Opts
emby_docker_security_opts_default: []
emby_docker_security_opts_custom: []
emby_docker_security_opts: "{{ emby_docker_security_opts_default
                               + emby_docker_security_opts_custom }}"

# Restart Policy
emby_docker_restart_policy: unless-stopped

# State
emby_docker_state: started
