##########################################################################
# Title:         Saltbox: Remote | Default Variables                     #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Global
################################

user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

rclone_config_path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
rclone_vfs_cache_dir: ""
rclone_override_service: "{{ mounts_override }}"
rclone_service_template: "saltbox_managed_rclone_"

rclone_port_lookup: "{{ port_lookup_rclone.meta.port
                        if (port_lookup_rclone.meta.port is defined) and (port_lookup_rclone.meta.port | trim | length > 0)
                        else '5572' }}"
rclone_remort_port: "{{ lookup('vars', 'rclone_remote_' + item.remote + '_port', default=rclone_port_lookup) }}"

################################
# Rclone VFS Refresh
################################

rclone_vfs_refresh_interval: 86400
rclone_vfs_refresh_command: |-
  /usr/bin/rclone rc vfs/refresh recursive=true --url http://localhost:{{ rclone_remort_port }} _async=true
