##########################################################################
# Title:         Saltbox: Remote | Default Variables                     #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Global
################################

user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

rclone_config_path: "/home/{{ user.name }}/.config/rclone/rclone.conf"

################################
# Feeder
################################

feeder_mount_start_command: |-
  /usr/bin/rclone mount \
    --user-agent='{{ user_agent }}' \
    --config={{ rclone_config_path }} \
    --allow-other \
    --allow-non-empty \
    --copy-links \
    --fast-list \
    --dir-cache-time=1m \
    --max-read-ahead=200M \
    --umask=002 \
    --syslog \
    -v \
    feeder:/mnt/local /mnt/feeder

feeder_mount_stop_command: /bin/fusermount -uz /mnt/feeder

################################
# Rclone VFS
################################

rclone_vfs_mount_start_command: |-
  /usr/bin/rclone mount \
    --user-agent='{{ user_agent }}' \
    --config={{ rclone_config_path }} \
    --allow-other \
    --allow-non-empty \
    --rc \
    --rc-addr=localhost:5572 \
    --fast-list \
    --drive-skip-gdocs \
    --vfs-read-chunk-size=64M \
    --vfs-read-chunk-size-limit=2048M \
    --buffer-size=64M \
    --poll-interval=1m \
    --dir-cache-time=168h \
    --timeout=10m \
    --drive-chunk-size=64M \
    --umask=002 \
    --syslog \
    -v \
    {{ rclone.remote }}: /mnt/remote

rclone_vfs_mount_stop_command: /bin/fusermount -uz /mnt/remote

rclone_vfs_mount_start_post_command: |-
  /usr/bin/rclone rc vfs/refresh recursive=true --rc-addr localhost:5572 _async=true
