##########################################################################
# Title:         Cloudbox: Emby | Post-Install Tasks                     #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install | Wait 10 seconds
  wait_for:
    timeout: 10

# Sometimes docker will set transcodes folder to root after a restore.
- name: Post-Install | Ensure transcodes folder has the correct permissions
  file:
    path: "{{ emby_transcodes_path }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes

- name: Post-Install | Wait for '{{ emby_config_file_path | basename }}' to be created
  wait_for:
    path: "{{ emby_config_file_path }}"
    state: present

- name: Post-Install | Import '{{ emby_dlna_file_path | basename }}'
  copy:
    src: "dlna.xml"
    dest: "{{ emby_dlna_file_path }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no
