#########################################################################
# Title:         Saltbox: UnionFS | Docker | Daemon Tasks               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Docker | Daemon | Create override directory"
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0775"

- name: "Docker | Daemon | Import override file"
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: "0775"
    force: "{{ docker_service_force }}"

- name: "Docker | Daemon | Systemd daemon-reload"
  ansible.builtin.systemd:
    name: docker
    state: reloaded
    daemon_reload: true

- name: "Docker | Daemon | Restart docker service"
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: "Docker | Daemon | Wait for 30 seconds before commencing"
  ansible.builtin.wait_for:
    timeout: 30
