#########################################################################
# Title:         Saltbox: Tautulli Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Tautulli roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    tautulli_original_name: "{{ role }}"
    tautulli_name: "{{ role if not '-' in role else (role | replace('-', '_')) }}"
  with_items: "{{ tautulli_instances }}"
  loop_control:
    loop_var: role
