##########################################################################
# Title:         Cloudbox: Traefik | Default Variables                   #
# Author(s):     RXWatcher, salty                                        #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

traefik_name: traefik

################################
# Paths
################################

traefik_paths_folder: "{{ traefik_name }}"
traefik_paths_location: "{{ server_appdata_path }}/{{ traefik_paths_folder }}"
traefik_paths_folders_list:
  - "{{ traefik_paths_location }}"

################################
# Web
################################

traefik_web_subdomain: "dash"
traefik_web_domain: "{{ user.domain }}"
traefik_web_url: "{{ 'https://' + traefik_web_subdomain + '.' + traefik_web_domain
                      if (reverse_proxy_is_enabled)
                      else 'http://localhost:' + traefik_web_port }}"
traefik_metrics_subdomain: "metrics"
traefik_metrics_domain: "{{ user.domain }}"

################################
# DNS
################################

traefik_dns_record: "{{ traefik_web_subdomain }}"
traefik_dns_zone: "{{ traefik_web_domain }}"
traefik_metrics_dns_record: "{{ traefik_metrics_subdomain }}"
traefik_metrics_dns_zone: "{{ traefik_metrics_domain }}"

################################
# Traefik
################################

traefik_traefik_certresolver: "{{ traefik_default_certresolver }}"
traefik_traefik_enabled: yes

################################
# Docker
################################

# Container
traefik_docker_container: "{{ traefik_name }}"

# Image
traefik_docker_image_pull: yes
traefik_docker_image_tag: "latest"
traefik_docker_image: "traefik:{{ traefik_docker_image_tag }}"

# Ports
traefik_docker_ports_defaults:
  - "80:80/tcp"
  - "443:443/tcp"
traefik_docker_ports_custom: []
traefik_docker_ports: "{{ traefik_docker_ports_defaults
                              + traefik_docker_ports_custom}}"

# Envs
traefik_docker_envs_default:
  TZ: "{{ tz }}"
  CLOUDFLARE_EMAIL: "{{ cloudflare.email }}"
  CLOUDFLARE_API_KEY: "{{ cloudflare.api }}"
traefik_docker_envs_custom: {}
traefik_docker_envs_reverse_proxy: {}
traefik_docker_envs: "{{ traefik_docker_envs_default
                              | combine(traefik_docker_envs_custom)
                              | combine(traefik_docker_envs_reverse_proxy)}}"

# Commands
traefik_docker_commands_default:
  - "--global.sendanonymoususage=false"
  - "--providers.file.directory=/etc/traefik"
  - "--providers.docker=true"
  - "--providers.docker.exposedbydefault=false"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--entryPoints.websecure.forwardedHeaders.insecure"
  - "--entryPoints.websecure.proxyProtocol.insecure"
  - "--api.dashboard=true"
  - "--api=true"
  - "--certificatesresolvers.cfdns.acme.dnschallenge.provider=cloudflare"
  - "{{ '--certificatesresolvers.cfdns.acme.email=' + user.email }}"
  - "--certificatesresolvers.cfdns.acme.storage=/etc/traefik/acme.json"
  - "--certificatesresolvers.tlsresolver.acme.tlschallenge=true"
  - "{{ '--certificatesresolvers.tlsresolver.acme.email=' + user.email }}"
  - "--certificatesresolvers.tlsresolver.acme.storage=/etc/traefik/acme.json"

traefik_docker_commands_metrics:
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--metrics.prometheus.manualrouting=true"

traefik_docker_commands_custom: []
traefik_docker_commands: "{{ traefik_docker_commands_default
                              + traefik_docker_commands_custom 
                              if not (traefik.metrics)
                              else traefik_docker_commands_default
                              + traefik_docker_commands_custom 
                              + traefik_docker_commands_metrics }}"

# Volumes
traefik_docker_volumes_default:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
  - "{{ traefik_paths_location }}:/etc/traefik"
traefik_docker_volumes_custom: []
traefik_docker_volumes: "{{ traefik_docker_volumes_default
                                + traefik_docker_volumes_custom }}"

# Devices
traefik_docker_devices_default: []
traefik_docker_devices_custom: []
traefik_docker_devices: "{{ traefik_docker_devices_default
                                + traefik_docker_devices_custom }}"

# Hosts
traefik_docker_hosts_default: []
traefik_docker_hosts_custom: []
traefik_docker_hosts: "{{ docker_hosts_common
                              | combine(traefik_docker_hosts_default)
                              | combine(traefik_docker_hosts_custom) }}"

# Labels
traefik_docker_labels_default: 
  traefik.enable: "true"
  traefik.http.routers.traefik.rule: "Host(`{{ traefik_web_subdomain }}.{{ traefik_web_domain }}`)"
  traefik.http.routers.traefik.entrypoints: "websecure"
  traefik.http.routers.traefik.tls: "true"
  traefik.http.routers.traefik.tls.options: "securetls@file"
  traefik.http.routers.traefik.middlewares: "traefik-auth,gzip"
  traefik.http.routers.traefik.service: "api@internal"
  traefik.http.routers.redirs.rule: "hostregexp(`{host:.+}`)"  
  traefik.http.routers.redirs.entrypoints: "web"  
  traefik.http.routers.redirs.middlewares: "redirect-to-https"
  traefik.http.middlewares.traefik-auth.basicauth.usersfile: "/etc/traefik/auth"
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"  
  traefik.http.middlewares.gzip.compress: "true"

traefik_docker_labels_cloudflare_validation:
  traefik.http.routers.traefik.tls.certresolver: "cfdns"
  traefik.http.routers.traefik.tls.domains[0].main: "{{ user.domain }}"
  traefik.http.routers.traefik.tls.domains[0].sans: "{{ '*.' + user.domain }}"

traefik_docker_labels_tls_validation:
  traefik.http.routers.traefik.tls.certresolver: "tlsresolver"

traefik_docker_labels_metrics:
  traefik.http.routers.metrics.rule: "Host(`{{ traefik_metrics_subdomain }}.{{ traefik_metrics_domain }}`) && Path(`/prometheus`)"
  traefik.http.routers.metrics.service: prometheus@internal
  traefik.http.routers.metrics.entrypoints: "websecure"
  traefik.http.routers.metrics.tls: "true"
  traefik.http.routers.metrics.middlewares: "traefik-auth,gzip"

traefik_docker_labels_custom: {}

traefik_docker_labels_validation: "{{ traefik_docker_labels_cloudflare_validation 
                                    if not (traefik.tls)
                                    else traefik_docker_labels_tls_validation }}"

traefik_docker_labels_metrics_temp: "{{ [] 
                                    if not (traefik.metrics)
                                    else traefik_docker_labels_metrics }}"

traefik_docker_labels: "{{ traefik_docker_labels_default
                              | combine(traefik_docker_labels_custom) 
                              | combine(traefik_docker_labels_validation) 
                              | combine(traefik_docker_labels_metrics_temp) }}"

# Hostname
traefik_docker_hostname: "{{ traefik_name }}"

# Networks
traefik_docker_networks_alias: "{{ traefik_name }}"
traefik_docker_networks_default: []
traefik_docker_networks_custom: []
traefik_docker_networks: "{{ docker_networks_common
                                  + traefik_docker_networks_default
                                  + traefik_docker_networks_custom }}"

# Capabilities
traefik_docker_capabilities_default: []
traefik_docker_capabilities_custom: []
traefik_docker_capabilities: "{{ traefik_docker_capabilities_default
                                      + traefik_docker_capabilities_custom }}"

# Security Opts
traefik_docker_security_opts_default: []
traefik_docker_security_opts_custom: []
traefik_docker_security_opts: "{{ traefik_docker_security_opts_default
                                      + traefik_docker_security_opts_custom }}"

# Restart Policy
traefik_docker_restart_policy: unless-stopped

# State
traefik_docker_state: started