#########################################################################
# Title:         Saltbox: Backup | Cron Tasks                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Get ansible-playbook binary path."
  shell: "which ansible-playbook"
  register: playbook_binary

- name: "Remove legacy cron backup task."
  cron:
    name: "Backup Cloudbox"
    state: absent

- name: "Schedule cron backup."
  cron:
    name: "Cloudbox Backup"
    special_time: "{{ backup.cron.cron_time }}"
    job: "sudo PATH='/usr/bin:/bin:/usr/local/bin' env ANSIBLE_CONFIG='{{ playbook_dir }}/ansible.cfg' '{{ playbook_binary.stdout }}' '{{ playbook_dir }}/backup.yml' >> '{{ playbook_dir }}/cloudbox_backup.log' 2>&1"
    state: "{{ backup.cron.cron_state }}"
    user: "{{ user.name }}"
