#########################################################################
# Title:         Cloudbox: Radarr Role                                  #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent
    container_default_behavior: compatibility

- name: Create directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Import '98-themepark'
  template:
    src: "98-themepark.sh"
    dest: "{{ radarr_paths_location }}/98-themepark.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
