#########################################################################
# Title:         Cloudbox: Community Role                               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox2/cloudbox                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Migration Tasks
  import_tasks: "subtasks/migration.yml"

- name: Create Community directory
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775 recurse=yes"
  with_items:
    - /opt/community

- name: Clone Community repo 'HEAD'
  git:
    repo: https://github.com/cloudbox2/community.git
    dest: /opt/community
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: community_clone_status

- name: Clone Community repo 'master'
  git:
    repo: https://github.com/cloudbox2/community.git
    dest: /opt/community
    clone: true
    version: master
    force: true
  become: true
  become_user: "{{ user.name }}"
  when: community_clone_status is failed

- name: Create symlink to folder in '/home'
  file:
    src: /opt/community/
    dest: "/home/{{ user.name }}/community"
    state: link

- name: Import default files when missing
  copy:
    src: "{{ item }}"
    dest: "/opt/community/{{ (item | basename | splitext)[0] }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: false
  with_fileglob:
    - /opt/community/defaults/*.*

- name: ansible.cfg Tasks
  import_tasks: "subtasks/ansible_cfg.yml"
