#########################################################################
# Title:         Saltbox: System | Locale Tasks                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Locale | Install 'locales'"
  apt:
    name: locales
    state: present

- name: "Locale | Generate 'locales'"
  locale_gen:
    name: "en_US.UTF-8"
    state: present
  notify: Handers | Update 'locales'

- name: "Locale | Uncomment '#LANG='"
  replace:
    path: "/etc/default/locale"
    regexp: '^#(LANG=.*)'
    replace: '\1'
  ignore_errors: true

- name: "Locale | Set Default 'locale'"
  ini_file:
    path: "/etc/default/locale"
    section: null
    option: "LANG"
    value: "en_US.UTF-8"
    state: present
    create: true
    mode: '0644'
    no_extra_spaces: true
  notify: Handers | Update 'locales'
