########################################################################################
# Title:         Saltbox: Settings | Migrator | 'adv_settings.yml' | Migration 01      #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################

---
- name: Migrator | 'adv_settings.yml' | Migration 01 | Remove 'null' values
  replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(?<=: )\bnull\s*$'
    replace: ''
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: 0664

- name: Migrator | 'adv_settings.yml' | Migration 01 | Re-import Variables
  include_vars: "{{ playbook_dir }}/{{ file }}"
