########################################################################################
# Title:         Saltbox: Settings | Migrator | 'adv_settings.yml' | Migration 01      #
# Author(s):     desimaniac, salty                                                     #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################

---
- name: "Migrator | 'adv_settings.yml' | Migration 01 | Set variables"
  ansible.builtin.set_fact:
    traefik_tls_settings: "{{ not ((traefik is undefined)
                              or
                              (traefik is none)
                              or
                              (traefik | trim | length == 0)
                              or
                              (traefik.tls is undefined)
                              or
                              (traefik.tls is none)
                              or
                              (traefik.tls | trim | length == 0)) }}"
    traefik_metrics_settings: "{{ not ((traefik is undefined)
                                  or
                                  (traefik is none)
                                  or
                                  (traefik | trim | length == 0)
                                  or
                                  (traefik.metrics is undefined)
                                  or
                                  (traefik.metrics is none)
                                  or
                                  (traefik.metrics | trim | length == 0)) }}"
    old_dockerhub: "{{ not ((dockerhub is undefined)
                       or
                       (dockerhub is none)
                       or
                       (dockerhub | trim | length == 0)) }}"
    old_dns_enabled: "{{ not ((dns.enabled is undefined)
                         or
                         (dns.enabled is none)
                         or
                         (dns.enabled | trim | length == 0)) }}"
    old_feeder_mount: "{{ not ((mounts.feeder is undefined)
                          or
                          (mounts.feeder is none)
                          or
                          (mounts.feeder | trim | length == 0)) }}"
    old_remote_mount: "{{ not ((mounts.remote is undefined)
                          or
                          (mounts.remote is none)
                          or
                          (mounts.remote | trim | length == 0)) }}"

- name: Migrator | 'adv_settings.yml' | Migration 01 | Rebuild 'traefik.tls' dict
  ansible.builtin.shell: |
    yyq e -i '.traefik.tls = "no"' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (not traefik_tls_settings)

- name: Migrator | 'adv_settings.yml' | Migration 01 | Rebuild 'traefik.metrics' dict
  ansible.builtin.shell: |
    yyq e -i '.traefik.metrics = "no"' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (not traefik_metrics_settings)

- name: Migrator | 'adv_settings.yml' | Migration 01 | Delete 'dockerhub' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.dockerhub)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_dockerhub

- name: Migrator | 'adv_settings.yml' | Migration 01 | Delete 'dns.enabled' key-pair
  ansible.builtin.shell: |
    yyq e -i 'del(.dns.enabled)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_dns_enabled

- name: Migrator | 'adv_settings.yml' | Migration 01 | Delete 'mounts.feeder' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.mounts.feeder)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_feeder_mount

- name: Migrator | 'adv_settings.yml' | Migration 01 | Delete 'mounts.remote' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.mounts.remote)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_remote_mount

- name: Migrator | 'adv_settings.yml' | Migration 01 | Remove 'null' values
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(?<=: )\bnull\s*$'
    replace: ''
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: 0664

- name: Migrator | 'adv_settings.yml' | Migration 01 | Re-import Variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/{{ file }}"
