#########################################################################
# Title:            Saltbox: Autoscan                                   #
# Author(s):        Salty, TABLE                                        #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Autoscan roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    autoscan_original_name: "{{ role }}"
    autoscan_name: "{{ role if not '-' in role else (role | replace('-', '_')) }}"
  with_items: "{{ autoscan_instances }}"
  loop_control:
    loop_var: role
