#########################################################################
# Title:         Saltbox: qBittorrent | Post-Install Tasks              #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config to be created
  ansible.builtin.wait_for:
    path: "{{ qbittorrent_paths_conf }}"
    state: present

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Stop container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"
  when: not qbittorrent_host_install

- name: Post-Install | Stop '{{ qbittorrent_original_name }}.service'
  ansible.builtin.systemd:
    name: "{{ qbittorrent_original_name }}.service"
    state: stopped
    enabled: true
  when: qbittorrent_host_install

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Post-Install | Start container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
  when: not qbittorrent_host_install

- name: Post-Install | Start '{{ qbittorrent_original_name }}.service'
  ansible.builtin.systemd:
    name: "{{ qbittorrent_original_name }}.service"
    state: started
    enabled: true
  when: qbittorrent_host_install
