##########################################################################
# Title:         Saltbox: Authelia | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

authelia_name: authelia

################################
# Configuration
################################

# Options are file or ldap
authelia_authentication_backend: "file"

# Setting for default Access Control Policy
# Reference: https://www.authelia.com/configuration/security/access-control/#one_factor
authelia_access_control_policy: "one_factor"

# Settings for Duo
# Reference: https://www.authelia.com/configuration/second-factor/duo/
authelia_duo_enabled: false
authelia_duo_hostname: ""
authelia_duo_integration_key: ""
authelia_duo_secret_key: ""
authelia_duo_self_enrollment: "true"

# Settings for Webauthn
# Reference: https://www.authelia.com/configuration/second-factor/webauthn/
authelia_webauthn_disable: false
authelia_webauthn_display_name: "Authelia"
authelia_webauthn_attestation_conveyance_preference: "indirect"
authelia_webauthn_user_verification: "preferred"
authelia_webauthn_timeout: "60s"

# Settings for Notifier
# Reference: https://www.authelia.com/configuration/notifications/introduction/
authelia_notifier: "filesystem"
authelia_notifier_disable_startup_check: "false"
authelia_notifier_smtp_host: ""
authelia_notifier_smtp_port: ""
authelia_notifier_smtp_timeout: ""
authelia_notifier_smtp_username: ""
authelia_notifier_smtp_password: ""
authelia_notifier_smtp_sender: ""
authelia_notifier_smtp_identifier: ""
authelia_notifier_smtp_subject: ""
authelia_notifier_smtp_startup_check_address: ""
authelia_notifier_smtp_disable_require_tls: ""
authelia_notifier_smtp_disable_html_emails: ""
authelia_notifier_smtp_tls_server_name: ""
authelia_notifier_smtp_tls_skip_verify: ""
authelia_notifier_smtp_tls_minimum_version: ""

################################
# Paths
################################

authelia_paths_folder: "{{ authelia_name }}"
authelia_paths_location: "{{ server_appdata_path }}/{{ authelia_paths_folder }}"
authelia_paths_folders_list:
  - "{{ authelia_paths_location }}"

################################
# Web
################################

authelia_web_subdomain: "{{ authelia.subdomain }}"
authelia_web_domain: "{{ user.domain }}"
authelia_web_port: "9091"
authelia_web_url: "{{ 'https://' + authelia_web_subdomain + '.' + authelia_web_domain }}"

################################
# DNS
################################

authelia_dns_record: "{{ authelia_web_subdomain }}"
authelia_dns_zone: "{{ authelia_web_domain }}"
authelia_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

authelia_traefik_sso_middleware: ""
authelia_traefik_middleware_default: "{{ traefik_default_middleware }}"
authelia_traefik_middleware_custom: ""
authelia_traefik_certresolver: "{{ traefik_default_certresolver }}"
authelia_traefik_enabled: true
authelia_traefik_api_enabled: false
authelia_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
authelia_docker_container: "{{ authelia_name }}"

# Image
authelia_docker_image_pull: true
authelia_docker_image_tag: "4.37"
authelia_docker_image: "authelia/authelia:{{ authelia_docker_image_tag }}"

# Ports
authelia_docker_ports_defaults: []
authelia_docker_ports_custom: []
authelia_docker_ports: "{{ authelia_docker_ports_defaults
                           + authelia_docker_ports_custom }}"

# Envs
authelia_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
authelia_docker_envs_custom: {}
authelia_docker_envs: "{{ authelia_docker_envs_default
                          | combine(authelia_docker_envs_custom) }}"

# Commands
authelia_docker_commands_default: []
authelia_docker_commands_custom: []
authelia_docker_commands: "{{ authelia_docker_commands_default
                              + authelia_docker_commands_custom }}"

# Volumes
authelia_docker_volumes_default:
  - "{{ authelia_paths_location }}:/config"
authelia_docker_volumes_custom: []
authelia_docker_volumes: "{{ authelia_docker_volumes_default
                             + authelia_docker_volumes_custom }}"

# Devices
authelia_docker_devices_default: []
authelia_docker_devices_custom: []
authelia_docker_devices: "{{ authelia_docker_devices_default
                             + authelia_docker_devices_custom }}"

# Hosts
authelia_docker_hosts_default: []
authelia_docker_hosts_custom: []
authelia_docker_hosts: "{{ docker_hosts_common
                           | combine(authelia_docker_hosts_default)
                           | combine(authelia_docker_hosts_custom) }}"

# Labels
authelia_docker_labels_default: {}
authelia_docker_labels_custom: {}
authelia_docker_labels: "{{ docker_labels_common
                            | combine(authelia_docker_labels_default)
                            | combine(authelia_docker_labels_custom) }}"

# Hostname
authelia_docker_hostname: "{{ authelia_name }}"

# Networks
authelia_docker_networks_alias: "{{ authelia_name }}"
authelia_docker_networks_default: []
authelia_docker_networks_custom: []
authelia_docker_networks: "{{ docker_networks_common
                              + authelia_docker_networks_default
                              + authelia_docker_networks_custom }}"

# Capabilities
authelia_docker_capabilities_default: []
authelia_docker_capabilities_custom: []
authelia_docker_capabilities: "{{ authelia_docker_capabilities_default
                                  + authelia_docker_capabilities_custom }}"

# Security Opts
authelia_docker_security_opts_default: []
authelia_docker_security_opts_custom: []
authelia_docker_security_opts: "{{ authelia_docker_security_opts_default
                                   + authelia_docker_security_opts_custom }}"

# Restart Policy
authelia_docker_restart_policy: always

# State
authelia_docker_state: started
