#########################################################################
# Title:         Saltbox: Docker | Daemon Tasks                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create docker directory
  file: "path={{ item }} state=directory mode=0775 owner=root group=root"
  with_items:
    - /etc/docker

- name: "Daemon | Import 'daemon.json'"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0775
    force: true

- name: "Daemon | Create override directory"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0775

- name: "Daemon | Import override file"
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0775
    force: false

- name: "Daemon | Edit override file"
  ini_file:
    path: /etc/systemd/system/docker.service.d/override.conf
    section: Unit
    option: "After"
    value: "{{ mount_type }}.service"
    state: present
    mode: '0755'
    no_extra_spaces: true
