#########################################################################
# Title:         Saltbox: Docker | Docker Hub Tasks                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Docker Hub | Login
  shell: "docker login -u {{ dockerhub.user }} -p {{ dockerhub.token }}"
  no_log: true

- name: Docker Hub | Login
  shell: "docker login -u {{ dockerhub.user }} -p {{ dockerhub.token }}"
  become: true
  become_user: "{{ user.name }}"
  no_log: true
