##########################################################################
# Title:         Cloudbox: Plex Extra Tasks | Default Variables          #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

plex_name: "plex"

################################
# Folders
################################

plex_folder: "{{ plex_name }}"

app_folder: "{{ plex_folder }}"

################################
# Files
################################

plex_application_support_path: "{{ server_appdata_path }}/{{ app_folder }}/Library/Application Support/Plex Media Server"

plex_config_file_path: "{{ plex_application_support_path }}/Preferences.xml"

plex_db_path: "{{ plex_application_support_path }}/Plug-in Support/Databases/com.plexapp.plugins.library.db"

################################
# Docker Container
################################

plex_docker_name: "{{ plex_name }}"

docker_name: "{{ plex_docker_name }}"

################################
# Docker State
################################

plex_docker_state: started

docker_state: "{{ plex_docker_state }}"
