#########################################################################
# Title:         Saltbox: MariaDB Migration                             #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for '/opt/{{ mariadb_name }}/databases'
  ansible.builtin.stat:
    path: "/opt/{{ mariadb_name }}/databases"
  register: folder

- name: Move contents of '/opt/{{ mariadb_name }}/databases' to '/opt/{{ mariadb_name }}'
  ansible.builtin.shell: |
    mv "/opt/{{ mariadb_name }}/databases/*"  "/opt/{{ mariadb_name }}/"
    find "/opt/{{ mariadb_name }}/*" -type d -empty -delete
  when: folder.stat.exists
