#########################################################################
# Title:         Saltbox: MariaDB Pre-Migration                         #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for '/opt/mariadb/databases'
  ansible.builtin.stat:
    path: "/opt/mariadb/databases"
  register: folder

- name: Import databases
  block:

    - name: Wait for 10 seconds
      ansible.builtin.wait_for:
        timeout: 30

    - name: Import databases
      community.mysql.mysql_db:
        login_host: "mariadb"
        login_user: "root"
        login_password: "{{ mariadb_docker_env_password }}"
        state: import
        name: all
        target: /tmp/dump.sql
      register: import

    - name: Remove '/opt/mariadb/databases'
      ansible.builtin.file:
        path: /opt/mariadb/databases
        state: absent
      when: import.rc == 0

  when: folder.stat.exists
