#########################################################################
# Title:         Saltbox: MariaDB Pre-Migration                         #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for 'dump.sql'
  ansible.builtin.stat:
    path: "/opt/mariadb_legacy/dump.sql"
  register: dump

- name: Import databases
  when: (not folder.stat.exists and dump.stat.exists)
  block:
    - name: Wait for 5 seconds
      ansible.builtin.wait_for:
        timeout: 5

    - name: Import databases
      community.mysql.mysql_db:
        login_host: "mariadb"
        login_user: "root"
        login_password: "{{ mariadb_docker_env_password }}"
        state: import
        name: all
        target: /opt/mariadb_legacy/dump.sql
