#########################################################################
# Title:         Saltbox: MariaDB Pre-Migration                         #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for '/opt/mariadb/databases'
  ansible.builtin.stat:
    path: "/opt/mariadb/databases"
  register: folder

- name: Dump databases
  community.mysql.mysql_db:
    login_host: "mariadb"
    login_user: "root"
    login_password: "{{ mariadb_docker_envs_mysql_root_password }}"
    state: dump
    name: all
    target: /tmp/dump.sql
  when: folder.stat.exists
