#########################################################################
# Title:         Cloudbox: Docker | Binary Tasks                        #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Uninstall 'docker-py' pip module
  pip:
    name: docker-py
    state: absent
  ignore_errors: yes

- name: Binary | Add official gpg signing key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"

- name: Binary | Add official repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: yes

- name: Binary | Install 'docker-ce' and 'docker-ce-cli'
  include_tasks: "binary2.yml"
  loop:
    - {name: '{{ docker_ce_name }}', package: '{{ docker_ce_package }}', file_path: '{{ docker_ce_filepath }}', dpkg: '{{ docker_ce_dpkg }}'}
    - {name: '{{ docker_ce_cli_name }}', package: '{{ docker_ce_cli_package }}', file_path: '{{ docker_ce_cli_filepath }}', dpkg: '{{ docker_ce_cli_dpkg }}'}

- name: Binary | Install 'docker' pip module
  pip:
    name: docker
    state: latest
  ignore_errors: yes
