#########################################################################
# Title:         Saltbox: Docker | Binary Tasks                         #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Add official gpg signing key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"

- name: Binary | Add official repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: true

- name: Binary | Install Docker binaries
  include_tasks: "binary2.yml"
  loop:
    - 'containerd_io'
    - 'docker_ce'
    - 'docker_ce_cli'
