##########################################################################
# Title:         Cloudbox: Plex | Extra Tasks                            #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
# Sometimes docker will set transcodes folder to root after a restore.
- name: Extra | Ensure transcodes folder has the correct permissions
  file:
    path: "{{ plex.transcodes }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes

- name: Extra | Wait for 'Preferences.xml' to be created
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Preferences.xml"
    state: present

- name: Extra | Wait for Plex DB to be created
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"
    state: present

- name: Extra | Wait for Plex Media Server executable to be created
  shell: docker exec plex bash -c "ls '/usr/lib/plexmediaserver/Plex Media Server'"
  register: pms_check
  until: pms_check.stderr.find("No such file or directory") == -1
  retries: 600
  changed_when: pms_check.rc == 0
  failed_when: pms_check.rc == 1 or pms_check.rc > 2

- name: Extra | Stop Plex Container
  docker_container:
    name: plex
    state: stopped

- name: "Extra | DB Cache Size Settings"
  import_tasks: "subtasks/settings/db_cache_size.yml"
  tags: plex-db-cache-size

- name: "Extra | Forced Automatic Quality Settings"
  import_tasks: "subtasks/settings/forced_quality.yml"
  tags: plex-forced-quality

- name: "Extra | Install Sub-Zero Plugin"
  import_role:
    name: sub-zero-plugin

- name: "Extra | Install Trakt.tv Plugin"
  import_role:
    name: trakttv-plugin

- name: "Extra | Install WebTools Plugin"
  import_role:
    name: webtools-plugin

- name: Extra | Start Plex Container
  docker_container:
    name: plex
    state: started
