##########################################################################
# Title:         Cloudbox: Plex | Post-Install Tasks                     #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
# Sometimes docker will set transcodes folder to root after a restore.
- name: Post-Install | Ensure transcodes folder has the correct permissions
  file:
    path: "{{ plex.transcodes }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes

- name: Post-Install | Wait for 'Preferences.xml' to be created
  wait_for:
    path: "{{ plex_preferences_xml_path }}"
    state: present

- name: Post-Install | Wait for Plex DB to be created
  wait_for:
    path: "{{ plex_db_path }}"
    state: present

- name: Post-Install | Wait for Plex Media Server executable to be created
  shell: docker exec {{ docker_name }} bash -c "ls '/usr/lib/plexmediaserver/Plex Media Server'"
  register: pms_check
  until: pms_check.stderr.find("No such file or directory") == -1
  retries: 600
  changed_when: false
  failed_when: pms_check.rc == 1 or pms_check.rc > 2
