#########################################################################
# Title:            Saltbox: Autoscan                                   #
# Author(s):        salty, TABLE                                        #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Initialize an empty list for our strings
  ansible.builtin.set_fact:
    plex_tokens: []

- name: Token tasks
  ansible.builtin.include_tasks: token.yml
  loop: "{{ plex_instances }}"
  loop_control:
    loop_var: plex_instance

- name: Settings | Check if `{{ autoscan_paths_config_location | basename }}` exists
  ansible.builtin.stat:
    path: "{{ autoscan_paths_config_location }}"
  register: autoscan_config

- name: Settings | New `{{ autoscan_paths_config_location | basename }}` tasks
  block:

    - name: Settings | Import default `{{ autoscan_paths_config_location | basename }}`
      template:
        src: config.yml.j2
        dest: "{{ autoscan_paths_config_location }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0775

  when: not autoscan_config.stat.exists
