#########################################################################
# Title:         Cloudbox: UnionFS | MergerFS Tasks                     #
# Author(s):     EnorMOZ, desimaniac, salty                             #
# URL:           https://github.com/cloudbox2/cloudbox                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "MergerFS | Get URL for latest mergerfs release"
  shell: "{{ mergerfs_release_lookup_command }}"
  args:
    executable: /bin/bash
    warn: false
  register: mergerfs_download_url
  ignore_errors: true

- name: "MergerFS | Uninstall mergerfs"
  apt:
    name: mergerfs
    state: absent

- name: "MergerFS | Install mergerfs"
  apt:
    deb: "{{ mergerfs_download_url.stdout | default(mergerfs_download_backup_url, true) }}"
    state: present

- name: "MergerFS | Import 'mergerfs.service'"
  template:
    src: mergerfs.service.j2
    dest: /etc/systemd/system/mergerfs.service
    mode: '0755'
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: "MergerFS | Start 'mergerfs.service'"
  systemd:
    name: mergerfs.service
    state: started
    enabled: true
    daemon_reload: true
