#########################################################################
# Title:         Saltbox: DNS | Cloudflare | Add DNS Record             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Add DNS Record | Add DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: present
    solo: true
    proxied: "{{ dns.proxied | default('false') }}"
    type: A
    value: "{{ ip_address_public }}"
    record: "{{ dns_record }}"
  register: cloudflare_dns_record_creation_status

- name: Cloudflare | Add DNS Record | Tasks on success
  block:

    - name: Cloudflare | Add DNS Record | Set 'dns_record_print' variable
      set_fact:
        dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone,dns_record + '.' + dns_zone) }}"

    - name: Cloudflare | Add DNS Record | Display DNS Record creation status
      debug:
        msg: "DNS Record for '{{ dns_record_print }}' set to '{{ ip_address_public }}' was added."

  when: cloudflare_dns_record_creation_status is succeeded

- name: Cloudflare | IPv6 Block
  block:

    - name: Cloudflare | Add DNS Record | Add DNS Record
      cloudflare_dns:
        account_api_token: "{{ cloudflare.api }}"
        account_email: "{{ cloudflare.email }}"
        zone: "{{ dns_zone }}"
        state: present
        solo: true
        proxied: "{{ dns.proxied | default('false') }}"
        type: AAAA
        value: "{{ ipv6_address_public }}"
        record: "{{ dns_record }}"
      register: cloudflare_dns_v6_record_creation_status

    - name: Cloudflare | Add DNS Record | Tasks on success
      block:

        - name: Cloudflare | Add DNS Record | Set 'dns_record_print' variable
          set_fact:
            dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone,dns_record + '.' + dns_zone) }}"

        - name: Cloudflare | Add DNS Record | Display DNS Record creation status
          debug:
            msg: "DNS Record for '{{ dns_record_print }}' set to '{{ ipv6_address_public }}' was added."

      when: cloudflare_dns_v6_record_creation_status is succeeded

  when: dns.ipv6
