#########################################################################
# Title:         Cloudbox: NZBGet Role                                  #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/nzbget                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent
    container_default_behavior: compatibility

- name: Create directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: SMA Tasks
  include_tasks: "{{ resources_tasks_path }}/hotio/sickbeard_mp4_automator/install_reqs.yml"
  when:
    - ('hotio' in lookup('vars', role_name + '_docker_image'))
    - (use_sma)

- name: Docker Devices Task
  include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when:
    - (gpu.intel or gpu.nvidia)
    - (use_sma)

- name: Import '99-cont-init-script-runner.sh' script
  copy:
    src: "{{ resources_tasks_path }}/hotio/cont-init.d/files/99-cont-init-script-runner.sh"
    dest: "{{ lookup('vars', role_name + '_paths_location') }}/99-cont-init-script-runner.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: Import '98-themepark'
  template:
    src: "98-themepark.sh"
    dest: "{{ nzbget_paths_location }}/98-themepark.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: SMA Tasks
  include_tasks: "{{ resources_tasks_path }}/hotio/sickbeard_mp4_automator/install_reqs.yml"

- name: Check if existing config exists
  stat:
    path: "{{ nzbget_paths_config_location }}"
  register: nzbget_paths_config_location_stat

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
  when: not continuous_integration
