#########################################################################
# Title:         Saltbox: NZBGet Role                                   #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# Docker Image:  hotio/nzbget                                           #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Import '99-cont-init-script-runner.sh' script
  copy:
    src: "{{ resources_tasks_path }}/hotio/cont-init.d/files/99-cont-init-script-runner.sh"
    dest: "{{ lookup('vars', role_name + '_paths_location') }}/99-cont-init-script-runner.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: true

- name: Download 98-themepark
  get_url:
    url: "https://raw.githubusercontent.com/GilbN/theme.park/master/docker-mods/nzbget/root/etc/cont-init.d/98-themepark"
    dest: "{{ nzbget_paths_location }}/98-themepark.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    force: true

- name: Check if existing config exists
  stat:
    path: "{{ nzbget_paths_config_location }}"
  register: nzbget_paths_config_location_stat

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
  when: not continuous_integration
