########################################################################################
# Title:         Saltbox: Settings | Migrator | All | Migration 01                     #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: Migrator | All | '{{ file }}' | Migration 01 |
    Replace '{% raw -%}{{ user }}{%- endraw %}' with '{% raw -%}{{ user.name }}{%- endraw %}'
  replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '{% raw -%}{{\s*user\s*}}{%- endraw %}'
    replace: '{% raw -%}{{ user.name }}{%- endraw %}'
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: 0664

- name: Migrator | All | '{{ file }}' | Migration 01 | Re-import Variables
  include_vars: "{{ playbook_dir }}/{{ file }}"
