#########################################################################
# Title:         Saltbox: Remote | Basic Tasks                          #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Basics | Create mount directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775 recurse=yes"
  with_items: "{{ mount_paths }}"
