#########################################################################
# Title:         Saltbox: DNS Role                                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: DNS Tasks
  include_tasks: "main2.yml"
  vars:
    dns_record: "{{ _dns_role_record }}"
    dns_zone: "{{ _dns_role_zone }}"
    dns_action: "{{ _dns_role_action }}"
  when: reverse_proxy_is_enabled
