#########################################################################
# Title:         Cloudbox: Pre-Tasks                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox2/cloudbox                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always

- name: Chown '/srv/git/cloudbox'
  ansible.builtin.file:
    path: /srv/git/cloudbox
    state: directory
    recurse: true
    owner: uid
    group: gid
