#########################################################################
# Title:         Saltbox: Pre-Tasks                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  ansible.builtin.import_tasks: "subtasks/apt.yml"
  tags: always

- name: Git Tasks
  ansible.builtin.import_tasks: "subtasks/git.yml"
  tags: always

- name: Variables Tasks
  ansible.builtin.include_tasks: "subtasks/variables.yml"
  tags: always
