#########################################################################
# Title:         Saltbox: Pre-Tasks                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always

- name: Chown '/srv/git/saltbox'
  ansible.builtin.file:
    path: /srv/git/saltbox
    state: directory
    recurse: true
    owner: uid
    group: gid
