#########################################################################
# Title:         Cloudbox: Pre-Tasks                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Clean Paths
  import_tasks: "subtasks/clean_paths.yml"
  tags: always

- name: Set Cloudbox Variables
  import_tasks: "subtasks/variables.yml"
  tags: always

- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always
