##########################################################################
# Title:         Saltbox: Authelia | File Backend Task                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Check if 'users_database.yml' exists
  ansible.builtin.stat:
    path: "{{ authelia_paths_location }}/users_database.yml"
  register: authelia_user_config_stat

- name: "Generate Password Hash"
  community.docker.docker_container:
    name: authelia-password-hash
    image: "{{ authelia_docker_image }}"
    command: "authelia hash-password '{{ user.pass }}'"
    detach: no
    volumes:
      - "{{ authelia_paths_location }}:/config"
    networks:
      - name: saltbox
    purge_networks: yes
    cleanup: yes
    state: started
    container_default_behavior: compatibility
    tls_hostname: localhost
  register: authelia_password
  when: (not authelia_user_config_stat.stat.exists)

- name: "Sanitize Password Hash"
  ansible.builtin.shell: "echo '{{ authelia_password.container.Output }}' | sed -n 's/^Digest: //p'"
  register: authelia_password
  when: (not authelia_user_config_stat.stat.exists)

- name: Import default 'users_database.yml'
  ansible.builtin.template:
    src: users_database.yml.j2
    dest: "{{ authelia_paths_location }}/users_database.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: (not authelia_user_config_stat.stat.exists)
