##########################################################################
# Title:         Saltbox: Authelia | LDAP Backend Task                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: LDAP | Get FLD
  ansible.builtin.shell: |
    {{ saltbox_python }} -c "from tld import get_tld; res = get_tld(\"http://{{ authelia_web_domain | default(user.domain) }}\", as_object=True); print(res.tld)"
  register: authelia_tld

- name: LDAP | Get FLD
  ansible.builtin.shell: |
    {{ saltbox_python }} -c "from tld import get_tld; res = get_tld(\"http://{{ authelia_web_domain | default(user.domain) }}\", as_object=True); print(res.domain)"
  register: authelia_domain

- name: LDAP | Import OpenLDAP Role
  ansible.builtin.include_role:
    name: openldap

- name: LDAP | Import phpLDAPadmin Role
  ansible.builtin.include_role:
    name: phpldapadmin
