##########################################################################
# Title:         Cloudbox: Trakt.tv Plugin for Plex | Default Variables  #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

plex_name: "plex"

################################
# Folders
################################

plex_folder: "{{ plex_name }}"

plex_path: "{{ server_appdata_path }}/{{ plex_folder }}"

################################
# Paths
################################

plex_application_support_path: "{{ plex_path }}/Library/Application Support/Plex Media Server"

plex_plugins_path: "{{ plex_application_support_path }}/Plug-ins"

plex_plugin_trakttv_path: "{{ plex_plugins_path }}/Trakttv.bundle"

################################
# Repository
################################

plex_plugin_trakttv_release_url: https://api.github.com/repos/trakt/Plex-Trakt-Scrobbler/releases/latest

plex_plugin_trakttv_download_url_backup: https://github.com/trakt/Plex-Trakt-Scrobbler/releases/download/v1.3.3/trakt_for_plex-1.3.3-7f0f38e-linux_x86_64.zip

################################
# Docker Container
################################

plex_docker_container: "{{ plex_name }}"

################################
# Docker State
################################

plex_docker_state: started
