#########################################################################
# Title:         Saltbox: Notify Role                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Variables Task
  import_tasks: "subtasks/variables.yml"

- name: Sent Notification
  include_tasks: "subtasks/{{ item }}.yml"
  loop: "{{ notification_services }}"
