##########################################################################
# Title:         Saltbox: Hetzner NFS | Default Variables                #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
hetzner_nfs_init_overwrite: true
