#########################################################################
# Title:         Saltbox: DNS | Cloudflare                              #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Check if Cloudflare folder exists
  ansible.builtin.stat:
    path: "{{ cloudflare_path }}"
  register: cloudflare_folder

- name: Cloudflare | Setup
  ansible.builtin.include_tasks: "subtasks/setup.yml"
  when: (not cloudflare_folder.stat.exists) or cloudflare_reinstall

- name: Cloudflare | Add DNS Record
  ansible.builtin.include_tasks: "subtasks/add_dns_record.yml"
  when: dns_action != 'remove'

- name: Cloudflare | Remove DNS Record
  ansible.builtin.include_tasks: "subtasks/remove_dns_record.yml"
  when: dns_action == 'remove'
