#########################################################################
# Title:         Saltbox: System Handler                                #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Handers | Update 'locales'
  command: dpkg-reconfigure --frontend noninteractive locales
