#########################################################################
# Title:         Cloudbox: Plex Role                                    #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Variables Task
  import_tasks: "subtasks/variables.yml"

- name: Create DNS Record
  include_role:
    name: dns
  vars:
    record: "{{ subdomain }}"
  when: reverse_proxy_is_enabled

- name: Remove existing Docker container
  docker_container:
    name: "{{ docker_name }}"
    state: absent

- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items: "{{ folders }}"

- name: Preferences Tasks
  import_tasks: "subtasks/preferences/preferences.yml"
  when: (not continuous_integration)

- name: Create Docker container
  include_tasks: "{{ playbook_dir }}/resources/tasks/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install.yml"
