#########################################################################
# Title:         Cloudbox: Plex Role                                    #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Variables Task
  import_tasks: "subtasks/variables.yml"

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "{{ _subdomain }}"
  when:
    - cloudflare_enabled
    - reverse_proxy_is_enabled

- name: "Create directories"
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items: "{{ folders }}"

- name: "Stop and remove any existing container"
  docker_container:
    name: "{{ docker_name }}"
    state: absent

- name: Preferences Tasks
  import_tasks: "subtasks/preferences/preferences.yml"
  when: (not continuous_integration)

- name: "Create and start container"
  docker_container:
    name: "{{ docker_name }}"
    image: "{{ docker_image }}"
    pull: yes
    published_ports: "{{ docker_ports }}"
    env: "{{ docker_envs }}"
    volumes: "{{ docker_volumes }}"
    devices: "{{ docker_devices }}"
    etc_hosts: "{{ docker_hosts }}"
    labels: "{{ docker_labels }}"
    networks: "{{ docker_networks }}"
    purge_networks: yes
    restart_policy: "{{ docker_restart_policy }}"
    capabilities: "{{ docker_capabilities }}"
    security_opts: "{{ docker_security_opts }}"
    state: started

- name: Extra Tasks
  import_tasks: "subtasks/extra.yml"
  ignore_errors: yes
  tags: plex-extra-tasks
