name: CI

on:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'
      - 'roles/backup/**'
      - 'roles/restore/**'
      - 'roles/settings/**'
      - 'roles/nvidia/**'
      - 'roles/plex_extra_tasks/**'
      - 'roles/plex_auth_token/**'
      - 'roles/feeder/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'roles/backup/**'
      - 'roles/restore/**'
      - 'roles/settings/**'
      - 'roles/nvidia/**'
      - 'roles/plex_extra_tasks/**'
      - 'roles/plex_auth_token/**'
      - 'roles/feeder/**'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: curl https://raw.githubusercontent.com/saltyorg/sb/master/sb_dep.sh --output sb_dep.sh && sudo bash sb_dep.sh -v
        
      - name: Create /srv/git
        run: sudo mkdir /srv/git

      - name: Symlink cloned repository to /srv/git/saltbox
        run: sudo ln -s $GITHUB_WORKSPACE /srv/git/saltbox

      - name: Chown /srv/git
        run: sudo chown -R runner:runner /srv/git

      - name: Import default configuration
        run: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done

      - name: Edit accounts.yml
        run: sed -i 's/seed/runner/g' accounts.yml

      - name: Run Tree
        run: tree -a

      - name: Syntax Check
        run: sudo ansible-playbook saltbox.yml --syntax-check

      - name: Install Saltbox
        run: sudo ansible-playbook saltbox.yml --tags "saltbox,asshama,jellyfin,petio,prowlarr,transfer,emby,netdata,sabnzbd,sstv,autoheal,readarr,deluge,bazarr,qBittorrent" --skip-tags "settings,plex-extra-tasks" --extra-vars '{"continuous_integration":true}'

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
