#########################################################################
# Title:         Saltbox: Mainline Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install gnupg Dependencies
  ansible.builtin.apt:
    name: dirmngr

- name: Add launchpadcontent.net apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3AE27527713D2479DCAFFD58A89D7C1B2F76304D
    keyring: /usr/share/keyrings/launchpad.gpg

- name: Add cappelikan/ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:cappelikan/ppa
    state: present
    update_cache: true

- name: Install mainline
  ansible.builtin.apt:
    name: mainline
    state: present
